export const SET_PILLARS = 'SET_PILLARS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_LEVELS = 'SET_LEVELS';
export const SET_ARE_QUESTIONS_FETCHED = 'SET_ARE_QUESTIONS_FETCHED';
export const UPDATE_LEVEL = 'UPDATE_LEVEL';
